Error checking out a pull request which referenced branch has been deleted
sociomantic-tsunami/git-hub pull request #220
Opened 2017-07-08 21:08 UTC by daniel-zullo-sociomantic

The referenced branch has been deleted from an existent pull request.
Trying `git hub pull rebase --pause 123` gives the right error message
`It seems like the repository referenced by this pull request has been deleted`

However trying `git hub pull checkout 123` throws the error
```
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 2103, in <module>
    main()
  File "/usr/bin/git-hub", line 2097, in main
    args.run(parser, args)
  File "/usr/bin/git-hub", line 647, in check_config_and_run
    cmd.run(parser, args)
  File "/usr/bin/git-hub", line 1502, in run
    remote_url = pull['head']['repo'][config.urltype]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

2017-07-10 11:09 UTC, mathias-baumann-sociomantic approved these changes

2017-07-10 14:15 UTC, leandro-lucarella-sociomantic requested changes
Also, please rebase to v0.11.x

2017-07-10 14:15 UTC, leandro-lucarella-sociomantic commented on git-hub
> +                    "this pull request has been deleted")
I would say "Can't checkout pull request {id}, no head repository found (maybe it was deleted?)", or something like that.

2017-07-10 15:50 UTC, daniel-zullo-sociomantic commented
Changed the base branch to `v0.11.x` and updated the error message (I'm not entirely sure that's the right way to get the ID of the pull)

2017-07-20 16:14 UTC, leandro-lucarella-sociomantic approved these changes
Let me know if you want to change it or leave it as it is.

2017-07-20 16:14 UTC, leandro-lucarella-sociomantic commented on git-hub
> +                    "(maybe it was deleted?)", pull['number'])
Yeah, it's OK, you could also do this `die("Can't checkout pull request {number}, no head repository found (maybe it was deleted?)", pull)`, but it's essentially the same.

2017-07-20 18:10 UTC, daniel-zullo-sociomantic commented on git-hub
> +                    "(maybe it was deleted?)", pull['number'])
I think your suggestion looks better. I'll update it soon.

2017-07-21 12:03 UTC, daniel-zullo-sociomantic commented on git-hub
> +                    "(maybe it was deleted?)", pull['number'])
I'll have to use `**pull` instead, otherwise it won't work

2017-07-21 12:04 UTC, daniel-zullo-sociomantic commented
Previous head was c1b9c00, new head at c01ce26. Diff between heads are:
```diff
diff --git a/git-hub b/git-hub
index fd574bb..11febbb 100755
--- a/git-hub
+++ b/git-hub
@@ -1536,8 +1536,8 @@ class PullCmd (IssueCmd):
                     '(closed at {closed_at})!', **pull)
 
             if pull['head']['repo'] is None:
-                die("Can't checkout pull request {}, no head repository found "
-                    "(maybe it was deleted?)", pull['number'])
+                die("Can't checkout pull request {number}, no head repository "
+                    "found (maybe it was deleted?)", **pull)
 
             remote_url = pull['head']['repo'][config.urltype]
             remote_branch = pull['head']['ref']
```

2017-07-28 17:16 UTC, leandro-lucarella-sociomantic commented on git-hub
> +                    "(maybe it was deleted?)", pull['number'])
Right! Sorry.

2017-07-28 17:17 UTC, leandro-lucarella-sociomantic commented
So, have to tested it?

2017-07-28 17:17 UTC, leandro-lucarella-sociomantic commented
LGTM, I will merge after someone reports it is tested.

2017-08-02 14:51 UTC, daniel-zullo-sociomantic commented
Running the command `git-hub pull checkout 123` (on a private repository having an unknown repository branch in the PR), the current version of this patch reports:
`Error: Can't checkout pull request 123, no head repository found (maybe it was deleted?)`

While the version 0.11.0 of `git-hub` reports
```
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 2103, in <module>
    main()
  File "/usr/bin/git-hub", line 2097, in main
    args.run(parser, args)
  File "/usr/bin/git-hub", line 647, in check_config_and_run
    cmd.run(parser, args)
  File "/usr/bin/git-hub", line 1502, in run
    remote_url = pull['head']['repo'][config.urltype]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

2017-08-02 15:19 UTC, merged

2017-08-02 15:19 UTC, leandro-lucarella-sociomantic commented
Thanks!