`prefix` is missing for installing bash_completion
sociomantic-tsunami/git-hub pull request #222
Opened 2017-09-24 06:23 UTC by jean

```
--- a/Makefile
+++ b/Makefile
@@ -37,7 +37,7 @@ install: git-hub git-hub.1 ftdetect.vim bash-completion README.rst
        install -m 644 -D git-hub.1 $(DESTDIR)$(prefix)/share/man/man1/git-hub.1
        install -m 644 -D ftdetect.vim \
                $(DESTDIR)$(prefix)/share/vim/addons/ftdetect/githubmsg.vim
-       -install -m 644 -D bash-completion $(DESTDIR)/etc/bash_completion.d/git-hub
+       -install -m 644 -D bash-completion $(DESTDIR)$(prefix)/etc/bash_completion.d/git-hub
        install -m 644 -D README.rst $(DESTDIR)$(prefix)/share/doc/git-hub/README.rst
```

2017-09-12 10:15 UTC, leandro-lucarella-sociomantic commented
This is intentional. Bash completion normally should be in `/etc`, this is where bash looks for it. I don't see how adding the `prefix` will work.

2017-09-12 10:19 UTC, leandro-lucarella-sociomantic commented
I will close as invalid to avoid the issue to remain open forever if it doesn't get any further attention, but please reopen it if you still think this is wrong in any way.

2017-09-12 10:32 UTC, jean commented
I'm running this in [Termux](https://github.com/termux/) on Android. Termux doesn't have root and can't write to `/etc`. 

>  this is where bash looks for it.

At least on Ubuntu (and Mint, `/usr/share/bash-completion/bash_completion` has:

```
#   Copyright © 2006-2008, Ian Macdonald <ian@caliban.org>
#             © 2009-2013, Bash Completion Maintainers
#                     <bash-completion-devel@lists.alioth.debian.org>
[...]
# source user completion file
[[ ${BASH_SOURCE[0]} != ~/.bash_completion && -r ~/.bash_completion ]] \
    && . ~/.bash_completion
```

I could source git-hub and any other user-level completion files from there.

Now I'm using [bash-it](https://github.com/Bash-it/bash-it) and will load git-hub's completions using its [custom hook](https://github.com/Bash-it/bash-it#your-custom-scripts-aliases-themes-and-functions).

2017-09-12 10:39 UTC, jean commented
@leandro-lucarella-sociomantic looks like I can't reopen, so if you find my motivation convincing, please do.

2017-09-12 15:57 UTC, leandro-lucarella-sociomantic commented
Unfortunately I don't think the `make install` script can (or should) cover all possible installation scenarios out there. I think it is fair to ask the user to install the completion script manually if it is a weird case like this. `make install` shouldn't fail because it has a `-` in front that was added exactly because of this.

2017-09-12 19:20 UTC, jean commented
On 12 Sep 2017 11:07 pm, "Leandro Lucarella" <notifications@github.com>
wrote:

> Unfortunately I don't think the make install script can (or should) cover all possible installation scenarios out there. I think it is fair to ask the user to install the completion script manually if it is a weird case like this.

Seems to me acknowledging that support for `~/.bashcompletion` ships with
the biggest desktop distro isn't that weird, but OK. Point being that bash
is not limited to `/etc` for completion.
It's very commonly sourced from `.bashrc`, e.g. as recommended by [Pro Git](
https://git-scm.com/book/en/v2/Appendix-A:-Git-in-Other-Environments-Git-in-Bash
).

I mostly use `prefix` to install in `$HOME` because I want to leave the
system to be managed by `apt`, so I don't use `make` as root.

> `make install` shouldn't fail because it has a `-` in front that was added exactly because of this.

Yeah, I see that was after the last time I reported this ...
https://github.com/sociomantic-tsunami/git-hub/issues/93

Interesting, maybe the `make` failure was because Termux defaults to
busybox and didn't have a full-featured `make` installed at the time. I'll
check that out.

2017-09-15 10:22 UTC, leandro-lucarella-sociomantic commented
> Unfortunately I don't think the make install script can (or should) cover all possible installation scenarios out there.

I will insist in this statement. I believe there are many valid installation scenarios out there, but I think this is a packaging issue. If you think documentation on manual installation can be improved, PRs are welcome. I would even welcome a patch to add some variable where one can chose where to install the bash-completion script, but I don't plan to put any effort myself. I don't want to make `make install` smart enough to handle all possible environments in which one might would want to install, I think that's a lost battle.

If you use `apt`, the good news is `git-hub` is already in Debian and Ubuntu and you can actually do a `make deb` to create a package (you need `fpm` installed for this though).

2017-09-15 10:25 UTC, leandro-lucarella-sociomantic commented
Duplicate of #120

2017-09-15 11:33 UTC, jean commented
I certainly agree it shouldn't support all possible scenarios. I just think it should follow the principle of least surprise. 

I believe the precedent is set by autoconf, where `prefix` applies to all installed files, and can be overridden specifically for config files using `sysconfdir`. See [Installation Directory Variables](https://www.gnu.org/software/autoconf/manual/autoconf.html#Installation-Directory-Variables); here's a [SO answer](https://stackoverflow.com/a/8902781).

The only motivation that I've seen for not applying `prefix` to `/etc` is "_this is where bash looks for it_". However this is not true, where bash looks depends on the distro defaults and user configuration. Managing this is common, e.g. as exemplified by the quote from _Pro Git_ above; and various systems like [bash-it](http://github.com/Bash-it/bash-it), [compleat](https://github.com/mbrubeck/compleat), [bash-completion](https://github.com/scop/bash-completion), [complete](https://github.com/posener/complete), etc. exist to help manage completions that live elsewhere (generally in `$HOME`).

I could add partial support for `sysconfdir` like this:

```
-       -install -m 644 -D bash-completion $(DESTDIR)$(prefix)/etc/bash_completion.d/git-hub
+       install -m 644 -D bash-completion $(DESTDIR)${sysconfdir:-/etc}/bash_completion.d/git-hub
```

 though to conform to convention, it should fall back to  `prefix`. I think this would be more correct:

```
-       -install -m 644 -D bash-completion $(DESTDIR)$(prefix)/etc/bash_completion.d/git-hub
+       install -m 644 -D bash-completion $(DESTDIR)${sysconfdir:-$(prefix)/etc}/bash_completion.d/git-hub
```

2017-09-15 17:00 UTC, leandro-lucarella-sociomantic commented
autotools are waaaaaay more complex that what I want to see here. But as I said in #120, I'll be willing to accept a patch that introduces a `sysconfig` variable.

2017-09-15 17:01 UTC, leandro-lucarella-sociomantic commented
> though to conform to convention, it should fall back to prefix. I think this would be more correct:
> 
> -       -install -m 644 -D bash-completion $(DESTDIR)$(prefix)/etc/bash_completion.d/git-hub
> +       install -m 644 -D bash-completion $(DESTDIR)${sysconfdir:-$(prefix)/etc}/bash_completion.d/git-hub

This doesn't work to install in `/usr`, which is the main case I want to support to build the package.

2017-09-20 16:13 UTC, jean commented
I'm slowly understanding differences between `make` and `bash`  variables. How about this (ignore `PYTHON` please):

```
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,13 @@

 prefix ?= /usr/local

-export PYTHON := python
+# fall back to $prefix/etc (like autoconf)
+#sysconfdir := $(if $(sysconfdir),$(sysconfdir),$(prefix)/etc)
+
+# fall back to /etc (current behaviour)
+sysconfdir := $(if $(sysconfdir),$(sysconfdir),/etc)
+
+export PYTHON ?= python2

 version ?= $(shell git describe --dirty 2> /dev/null | cut -b2-)
 version := $(if $(version),$(version),devel)
@@ -37,7 +43,7 @@ install: git-hub git-hub.1 ftdetect.vim bash-completion README.rst
        install -m 644 -D git-hub.1 $(DESTDIR)$(prefix)/share/man/man1/git-hub.1
        install -m 644 -D ftdetect.vim \
                $(DESTDIR)$(prefix)/share/vim/addons/ftdetect/githubmsg.vim
-       -install -m 644 -D bash-completion $(DESTDIR)/etc/bash_completion.d/git-hub
+       install -m 644 -D bash-completion $(DESTDIR)$(sysconfdir)/bash_completion.d/git-hub
        install -m 644 -D README.rst $(DESTDIR)$(prefix)/share/doc/git-hub/README.rst

 .PHONY: release

2017-09-20 16:57 UTC, leandro-lucarella-sociomantic commented
> +sysconfdir := $(if $(sysconfdir),$(sysconfdir),/etc)

This is basically:
```make
sysconfdir ?= /etc
```

and I prefer that :)

2017-09-21 04:30 UTC, jean commented
Well, I prefer `sysconfdir ?= $(prefix)/etc`, but yes, quite correct! :-)
I'll make a PR with your preference.

2017-09-21 14:04 UTC, leandro-lucarella-sociomantic commented
Thanks.

If we used the `sysconfdir` to store config files which are read by ourselves, I would go for `$(prefix)/etc`, but since this is to install files used by someone else, and we can't control where bash_completion looks for files, and any `$(prefix)` that is not `/` or `/usr/local` or maybe `$HOME` probably won't work, I prefer to stay with a safer default (AKA `/etc), which at least should give you a hint that something failed (if the file is just copied in a place that bash_completion ignores, it will fail completely silently).

2017-09-24 06:26 UTC, jean commented
@leandro-lucarella-sociomantic 👀

2017-09-24 13:47 UTC, llucax requested changes
Other than the tiny comment, LGTM.

2017-09-24 13:47 UTC, llucax commented on Makefile
> +#sysconfdir ?= $(prefix)/etc)
I don't think this provides anything useful, once you need to override `sysconfdir` a fallback atlernative doesn't really matter.

2017-09-28 14:20 UTC, jean commented
Updated :-)

2017-09-28 14:29 UTC, leandro-lucarella-sociomantic commented
Thanks! I will take the liberty to squash both commits before merging :)

2017-09-28 14:32 UTC, leandro-lucarella-sociomantic commented
Merged as b977c3c8d06904970dd59e023f418fac4a96cc5f.

2017-09-28 14:32 UTC, closed without merging