Allow reusing of the last pull request title/descr
sociomantic-tsunami/git-hub pull request #238
Opened 2018-03-27 17:57 UTC by mathias-baumann-sociomantic

Sometimes pushing for various reason. If you typed a long detailed message and
don't remember to look in the HUB_EDITMSG file, you might just grumpily type it
again. With this you can just use -r to get your message back.

2018-04-04 17:05 UTC, jwilk commented
Thanks, I badly need something like this.
Should this be implemented for `issue new`, too? (Issue filing fails less often than creating PRs, but OTOH issue messages tend to be harder to retype.)
As a stop-gap measure you can use 
```console
$ git hub issue new -m "$(cat .git/HUB_EDITMSG)"
```
but this is inconvenient to type.

2018-04-10 15:53 UTC, leandro-lucarella-sociomantic commented
I agree this needs improving but I'm not crazy about the solution. I think it would make more sense to:

* If the Issue / PR was successfully created, then remove the `HUB_EDITMSG`).
* If it failed, keep it around.
* When creating a new issue / PR, check for the existence of  `HUB_EDITMSG` always, and if it's there, reuse it and maybe tell the user about this as a heading comment in the message (so worse case, they know they picked up an old file, and if they don't want it anymore, they can just manually remove it and re-run the program to get the default message based on the last commit).

2018-04-10 15:54 UTC, leandro-lucarella-sociomantic requested changes
In any case, I have a more general concern about this solution.

2018-04-16 09:59 UTC, mathias-baumann-sociomantic commented
So you'd be fine if I change it to your suggested solution?

2018-04-16 11:36 UTC, leandro-lucarella-sociomantic commented
Yes!

2018-11-07 17:03 UTC, leandro-lucarella-sociomantic commented
@mathias-baumann-sociomantic still interested in implementing this? :innocent:

2018-11-12 17:16 UTC, mathias-baumann-sociomantic commented
I have adjusted the commit according to your glorious comment

2018-11-12 17:42 UTC, leandro-lucarella-sociomantic approved these changes

2018-11-12 17:43 UTC, leandro-lucarella-sociomantic commented
Did you test this? Also @jwilk do you want to give this a try?

2018-11-13 11:34 UTC, mathias-baumann-sociomantic commented
Yes I did some testing. But not comprehensive, it can always use more

2018-11-16 11:30 UTC, jwilk commented on git-hub
> +        msg += help_msg
`msg` is None by default, so this explodes:
```console
$ ./git-hub issue new
Traceback (most recent call last):
  File "./git-hub", line 2175, in <module>
    main()
  File "./git-hub", line 2169, in main
    args.run(parser, args)
  File "./git-hub", line 661, in check_config_and_run
    cmd.run(parser, args)
  File "./git-hub", line 1199, in run
    msg = args.message or cls.editor()
  File "./git-hub", line 1092, in editor
    return editor(cls.help_msg, msg)
  File "./git-hub", line 306, in editor
    msg += help_msg
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

2018-11-19 10:24 UTC, mathias-baumann-sociomantic commented
I fixed the problem @jwilk discovered :)

2018-11-20 10:53 UTC, leandro-lucarella-sociomantic requested changes

2018-11-20 10:53 UTC, leandro-lucarella-sociomantic commented on git-hub
> +def editor(help_msg, msg=""):
It was previously important to distinguish between an user-provided empty message and no message provided at all. Not sure if this is still relevant, are you sure it is OK to change this?

2018-11-20 10:53 UTC, leandro-lucarella-sociomantic commented on git-hub
> +    if os.path.isfile(fname):
Yeah, actually I don't think this is quite right. If an user provides a new message you'll just discard it and use the old saved message instead. I don't think this is nice. You should probably leave the `None` as default and here first check `if msg is None and os.path.isfile(fname)` instead. Either that or always prepending, unconditionally, the old message if one is present.
```py
    if os.path.isfile(fname):
        with file(fname, 'r') as f:
            old_msg = PREV_MSG_HEADER + f.read()
    else:
        old_msg = ''
    # If a message was provided, use the old message as a comment
    if msg is not None:
        old_msg = ''.join('# ' + l for l in old_msg.splitlines(True))
    msg = old_msg + (msg or '') + help_msg
```
(untested)

2019-01-25 18:24 UTC, leandro-lucarella-sociomantic commented
@Marenz are you still willing to work on this or shall I close as abandoned?

2019-01-28 10:15 UTC, Marenz commented
I am willing, but this may take some months for me to pick up.. I suppose that means you can close it for now.

2019-01-28 14:38 UTC, leandro-lucarella-sociomantic commented
I'll leave it open as a reminder to ping you in some months ;)

2019-04-16 15:59 UTC, leandro-lucarella-sociomantic commented
Moving to Future milestone until it can be worked on again.

2019-09-03 13:10 UTC, leandro-lucarella-sociomantic commented
ping @Marenz

2020-10-27 13:32 UTC, llucax commented
> I am willing, but this may take some months for me to pick up.. I suppose that means you can close it for now.

OK, I will close it now, feel free to reopen if you suddenly want to pick it up again.

2020-10-27 13:32 UTC, closed without merging