git hub pull attach fails
sociomantic-tsunami/git-hub pull request #251
Opened 2019-01-04 16:32 UTC by leandro-lucarella-sociomantic

I get this:
```
~/src $ git hub pull attach 98 
Pushing branch to branch in origin
Attaching commits in branch branch to issue #98 (to be merged to owner/repo:master)
Error: GitHub error: Invalid request.

For 'properties/issue', "98" is not an integer.

```

2019-01-04 16:27 UTC, leandro-lucarella-sociomantic commented
This is probably due to https://developer.github.com/changes/2018-09-25-stricter-validation-coming-soon-in-the-rest-api/ and some missing conversions.

Can you attach the output of `git hub -v pull attach 98`?

2019-01-04 16:34 UTC, leandro-lucarella-sociomantic commented
Fix attached. I attached the code using `git-hub` with the fix applied :laughing: , so I guess the fix should work, but if you can, please do test it too.

2019-01-04 16:34 UTC, leandro-lucarella-sociomantic commented
Fix attached. I attached the code using `git-hub` with the fix applied :laughing: , so I guess the fix should work, but if you can, please do test it too.

2019-01-21 14:54 UTC, leandro-lucarella-sociomantic commented
@daniel-zullo-sociomantic can you test this?

2019-01-22 11:09 UTC, daniel-zullo commented on git-hub
> +                nargs='+', metavar=cls.id_var, type=int,
This change does not work and it isn't actually needed

```
./git-hub issue show 902
Traceback (most recent call last):
  File "../git-hub/git-hub", line 2156, in <module>
    main()
  File "../git-hub/git-hub", line 2150, in main
    args.run(parser, args)
  File "../git-hub/git-hub", line 649, in check_config_and_run
    cmd.run(parser, args)
  File "../git-hub/git-hub", line 1155, in run
    issue = req.get(cls.url(n))
  File "../git-hub/git-hub", line 1075, in url
    s += '/' + number
TypeError: cannot concatenate 'str' and 'int' objects
```

2019-01-22 11:18 UTC, daniel-zullo-sociomantic commented on git-hub
> +            parser.add_argument('-M', '--milestone', metavar='ID', type=int,
This one works fine

2019-01-22 11:20 UTC, daniel-zullo-sociomantic commented on git-hub
> +            parser.add_argument('issue', metavar=cls.id_var, type=int,
Works

2019-01-22 11:22 UTC, daniel-zullo-sociomantic commented on git-hub
> +            parser.add_argument('issue', metavar=cls.id_var, type=int,
works

2019-01-22 11:24 UTC, daniel-zullo commented on git-hub
> +            parser.add_argument('issue', metavar=cls.id_var, type=int,
it does not work
```
 ../git-hub/git-hub issue close 908
Traceback (most recent call last):
  File "../git-hub/git-hub", line 2156, in <module>
    main()
  File "../git-hub/git-hub", line 2150, in main
    args.run(parser, args)
  File "../git-hub/git-hub", line 649, in check_config_and_run ../git-hub/git-hub issue close 908
Traceback (most recent call last):
  File "../git-hub/git-hub", line 2156, in <module>
    main()
  File "../git-hub/git-hub", line 2150, in main
    args.run(parser, args)
  File "../git-hub/git-hub", line 649, in check_config_and_run
    cmd.run(parser, args)
  File "../git-hub/git-hub", line 1308, in run
    issue = req.patch(cls.url(args.issue), state='closed')
  File "../git-hub/git-hub", line 1075, in url
    s += '/' + number
TypeError: cannot concatenate 'str' and 'int' objects

    cmd.run(parser, args)
  File "../git-hub/git-hub", line 1308, in run
    issue = req.patch(cls.url(args.issue), state='closed')
  File "../git-hub/git-hub", line 1075, in url
    s += '/' + number
TypeError: cannot concatenate 'str' and 'int' objects
```

2019-01-22 11:48 UTC, daniel-zullo-sociomantic commented on git-hub
> +            parser.add_argument('pull', type=int,
It does not work 
```
../git-hub/git-hub pull checkout 907
Traceback (most recent call last):
  File "../git-hub/git-hub", line 2156, in <module>
    main()
  File "../git-hub/git-hub", line 2150, in main
    args.run(parser, args)
  File "../git-hub/git-hub", line 649, in check_config_and_run
    cmd.run(parser, args)
  File "../git-hub/git-hub", line 1548, in run
    pull = req.get(cls.url(args.pull))
  File "../git-hub/git-hub", line 1075, in url
    s += '/' + number
TypeError: cannot concatenate 'str' and 'int' objects
```

2019-01-22 11:49 UTC, daniel-zullo-sociomantic commented on git-hub
> +            parser.add_argument('issue', metavar='ISSUE', type=int,
works

2019-01-22 11:56 UTC, daniel-zullo requested changes
Many of the changes do not work.

You might need to fix update the `url()` method for the changes to work by converting the number to a string
https://github.com/sociomantic-tsunami/git-hub/blob/v1.0.x/git-hub#L1071-L1076

2019-01-23 12:13 UTC, daniel-zullo-sociomantic commented
```diff
diff --git a/git-hub b/git-hub
index b0f186d..5d83ffe 100755
--- a/git-hub
+++ b/git-hub
@@ -1072,7 +1072,7 @@ class IssueUtil (object):
     def url(cls, number=None):
         s = '/repos/%s/%s' % (config.upstream, cls.gh_path)
         if number:
-            s += '/' + number
+            s += '/' + str(number)
         return s
 
     @classmethod
```

2019-01-24 18:24 UTC, leandro-lucarella-sociomantic commented
Thanks for the testing! Yeah, I will have another look and do the conversion where it makes sense, I think it is better to use an `int` to store the PR/issue IDs as it also means we have some basic check on the args parser.

2019-01-24 18:30 UTC, leandro-lucarella-sociomantic commented
Updated.

2019-01-25 12:17 UTC, daniel-zullo approved these changes
LGTM

2019-01-25 16:00 UTC, merged

2019-01-25 16:03 UTC, leandro-lucarella-sociomantic commented
v1.0.3 released