Support issue and pull request templates
sociomantic-tsunami/git-hub pull request #274
Opened 2019-11-17 18:03 UTC by daniel-zullo-sociomantic

The command `git-hub issue new` and `git-hub pull new` accept
`--template` or `-t` to add template contents to the issue or
pull request body respectively.

Looks for a template file in the root directory of the project,
the `.github` directory and the `.git` directory until the first
template file is found. Then reads the content from the template
file found and adds it to the body of the issue or pull request.

The supported file names for issue templates are `ISSUE_TEMPLATE`
and `ISSUE_TEMPLATE.md`, and for pull request templates are
`PULL_REQUEST_TEMPLATE` and `PULL_REQUEST_TEMPLATE.md`.
The order for template lookups matters meaning that a template
file name without extension is looked up first followed by the
template file name with extension `.md`.

Finally note that only the content of the first issue or pull
request template found is added to the body of the issue or pull
request respectively.

Addresses #273

2019-11-17 18:05 UTC, daniel-zullo-sociomantic commented
Blocked on #262

2019-11-22 08:18 UTC, joshtriplett commented
If you're writing pull requests entirely using git-hub, you might not notice that a project uses a pull request template and realize you should use `-t`. Would you consider either making that the default (and having a `--no-template` to opt out), or at least putting a note in the pull request message body warning the user that the repository has an issue template and telling them how to use it?

2019-11-24 22:05 UTC, daniel-zullo-sociomantic commented
> If you're writing pull requests entirely using git-hub, you might not notice that a project uses a pull request template and realize you should use `-t`. Would you consider either making that the default (and having a `--no-template` to opt out), or at least putting a note in the pull request message body warning the user that the repository has an issue template and telling them how to use it?

Then it makes sense to use the templates by default and disable them if a parameter is passed.

2019-11-24 23:07 UTC, daniel-zullo-sociomantic commented
Updated based on suggestions from @joshtriplett
Though I still need to test it and probably update/fix it accordingly

2019-11-25 16:22 UTC, joshtriplett commented
Looks great, thank you!

2020-08-18 13:29 UTC, llucax commented
As the idea is to move this to use Python3 and v2.0.0 will be released for this, it might be a good time to give this some final love if you want it to be included in v2.0.0. Otherwise it will wait for an eventual v2.1.0.

2020-08-18 13:32 UTC, llucax requested changes
Please don't forget to update the README/man page too.

2020-08-19 14:42 UTC, daniel-zullo-sociomantic commented
I will update it soon (probably this evening). I'll replace lists with tuples and update documentation

2020-08-19 20:04 UTC, daniel-zullo-sociomantic commented
Amended changes and updated documentation in `man.rst`

2020-08-20 09:51 UTC, llucax approved these changes
LGTM but I don't dare to merge as I haven't tested it yet. Have you?

I have the feeling that at some point it would make sense to add a `--template` option but I guess it would not be different from the option to pick a template that fit offers.

2020-08-24 08:59 UTC, daniel-zullo-sociomantic commented
> I don't dare to merge as I haven't tested it yet. Have you?

Yes, I have tested creating new issues and PR with and without templates. Everything worked smoothly for me. 

> I have the feeling that at some point it would make sense to add a --template option but I guess it would not be different from the option to pick a template that fit offers.

Right, that'd be useful in case you need to handle more than one issue/PR template.

2020-08-25 12:14 UTC, llucax commented
OK, I'll merge then :crossed_fingers:

2020-08-25 12:15 UTC, merged